services:
  bot:
    build: .
    restart: always
    stop_signal: SIGINT
    environment:
      - BOT_TOKEN
      - DB_HOST
      - DB_USER
      - DB_PASS
      - DB_NAME
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "/var/lib/postgresql/data"
